/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/VfXKZdJO0KQ
 */
import Link from "next/link";
import { Form } from "./form";

export function LandingPage() {
  const currentYear = new Date().getFullYear();

  return (
		<div className="flex flex-col min-h-[100dvh]">
			<header className="px-4 lg:px-6 h-14 flex items-center">
				<Link className="flex items-center justify-center" href="#">
					<span className="sr-only">Tally Light Pro</span>
				</Link>
				<nav className="ml-auto flex gap-4 sm:gap-6">
					<Link className="text-sm font-medium hover:underline underline-offset-4" href="#features">
						Features
					</Link>
					<Link
						className="text-sm font-medium hover:underline underline-offset-4"
						href="https://github.com/mackenly/tally-light-app/issues"
						target="_blank"
					>
						Support
					</Link>
					<Link className="text-sm font-medium hover:underline underline-offset-4" href="#sign-up">
						Sign up
					</Link>
				</nav>
			</header>
			<main className="flex-1">
				<section className="w-full py-6 md:py-12 lg:py-16 flex items-center justify-center">
					<div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
						<div className="space-y-3">
							<h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl">
								Introducing Tally Light Pro
							</h1>
							<p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
								The app that lets you monitor your camera&apos;s tally data from any mobile device. Supporting a wide range
								of switcher systems.
							</p>
						</div>
						<img
							alt="Image"
							className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full pd:w-3/4 lg:w-5/6"
							height="310"
							src="/simone-impei-4_-2HJBQH8Q-unsplash.jpg"
							width="550"
						/>
					</div>
				</section>
				<section className="w-full py-6 md:py-12 lg:py-16 flex items-center justify-center border-t border-gray-200">
					<div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
						<div className="space-y-3">
							<h2 id="features" className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
								Features
							</h2>
							<ul className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
								<li>- Integrations with popular switchers</li>
								<li>- Multiview for operators with multiple outputs</li>
								<li>- API mode for custom tally sources</li>
							</ul>
						</div>
					</div>
				</section>
				<section id="sign-up" className="w-full py-6 md:py-12 lg:py-16 flex items-center justify-center">
					<div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
						<div className="space-y-3">
							<h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Download the App</h2>
							<p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
								Sign up to be notified when the app is available for download.
							</p>
						</div>
						<Form />
					</div>
				</section>
			</main>
			<footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
				<p className="text-xs text-gray-500">© {currentYear} Tricities Media Group LLC. All rights reserved.</p>
				<nav className="sm:ml-auto flex gap-4 sm:gap-6">
					<Link
						className="text-xs hover:underline underline-offset-4"
						href="https://github.com/mackenly/tally-light-app"
						target="_blank"
					>
						GitHub
					</Link>
					<Link
						className="text-xs hover:underline underline-offset-4"
						href="https://github.com/mackenly/tally-light-app/issues"
						target="_blank"
					>
						Support
					</Link>
					<Link className="text-xs hover:underline underline-offset-4" href="#">
						Terms of Service
					</Link>
					<Link className="text-xs hover:underline underline-offset-4" href="#">
						Privacy
					</Link>
				</nav>
			</footer>
		</div>
  );
}
